version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:3.4.1@sha256:fe489211fcb07e08c50646fafb7baa868e5ac6e73e1563cb726d7456139875a0
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    - ./raw:/opt/bitnami/spark/raw:rw
    - ./rich:/opt/bitnami/spark/rich:rw
  networks:
    - project_network

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./raw:/opt/airflow/raw
    - ./rich:/opt/airflow/rich
  depends_on:
    - postgres
  networks:
    - project_network

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker-1:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-worker-2:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-worker-3:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-worker-4:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - project_network

  webserver:
    <<: *airflow-common
    command: webserver
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname test_owner --lastname test_owner --role Admin --email test_owner@gmail.com --password admin && airflow scheduler"

  postgres-datawarehouse:
      image: postgres:15
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
      volumes:
          - postgres-db-volume:/var/lib/postgresql/data
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./rich:/rich
      ports:
          - 5432:5432
      networks:
          - project_network
      command: ["postgres", "-c", "max_connections=300"]
  pgadmin:
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
          PGADMIN_DEFAULT_PASSWORD: 'teste'
      ports:
          - 16543:80
      volumes:
          - ./pgadmin4/servers.json:/pgadmin4/servers.json
      networks:
          - project_network

volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data
    pgadmin-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./pgadmin4/data

networks:
  project_network:
    driver: bridge
